//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsMain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public string Manager { get; set; }
        public string Faculty { get; set; }
    }
}
