//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsMain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIsciplines
    {
        public int DisciplineId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Semester { get; set; }
        public string Speciality { get; set; }
    }
}
