//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsMain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Position { get; set; }
        public Nullable<int> Number { get; set; }
        public string Department { get; set; }
        public string Discipline { get; set; }
    }
}
